server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-registry:8090/eureka}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: resourceService
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: songService
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: storageService
          uri: lb://storage-service
          predicates:
            - Path=/storages/**
        - id: resourceProcessor
          uri: lb://resource-processor
          predicates:
            - Path=/processor/**
        - id: kibana
          uri: http://kibana:5601
          predicates:
            - Path=/kibana/**
        - id: grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana/**

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO